version: '3.9'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app:create_app
      - DATABASE_URL=postgresql://achraf:Pearlexport58@host.docker.internal:5433/financial_db

